# Generated by Django 4.2.6 on 2024-05-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_answer_remove_question_owner_delete_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
